Feature/2 menu for pc and sp
frontend-conference-hokkaido-2024/landing-page-2024 pull request #11
Opened 2024-04-07 08:50 UTC by 618knot

## issue番号

close #2

## やったこと
### PC画面のメニュー
![image](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/82982400/4b239673-311f-4947-8cf6-1465e373c7df)

### スマホ画面のメニュー
![image](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/82982400/a115fa38-6f3a-496f-8ae8-ba0977323dfc)
![image](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/82982400/a75a9dc7-c2d0-43dd-bc9f-fd1eadc12868)

## (あえて)やらないこと

ちゃんとしたデザインが決まっていないはずなので、細かい場所やデザインについては後回しにします。
アニメーションとかも同様に後回しにします。

## その他

eslintに`import { Menu, X } from 'lucide-react';`で怒られています。
いくらか調べてみましたが、よくわからなかったのでよければ教えてください 🙏 
```md
Parse errors in imported module 'lucide-react': parserPath or languageOptions.parser is required! (undefined:undefined)eslint[import/namespace](https://github.com/import-js/eslint-plugin-import/blob/v2.29.1/docs/rules/namespace.md)
```

2024-04-07 09:48 UTC, WataruNishimura requested changes

2024-04-07 09:48 UTC, WataruNishimura commented on src/components/LinkMenu/LinkMenu.tsx
> +    text: string;
textをstringで受け取ると、例えばspanタグやiconを渡しておきたいときに利用できないため、childrenを使うようにしてください。

※HTMLとして文字列そのものは要素ではないため、以下のように書かれるのがよりHTMLらしいとも言えます
```jsx
<LinkButton>
  TALKS
</LinkButton>
```

2024-04-07 09:48 UTC, WataruNishimura commented on src/components/LinkMenu/LinkMenu.tsx
> +    url: string;
urlではなくhrefとし、何か明示してください。またこれだとtarget属性等が指定できないため<Link>要素のpropsをextendsするなどして残りのpropsをLinkタグに渡すなどするといいかもしれません
例えばhrefには、urlを文字列だけでなくObjectとして渡す機能があります。

```jsx
<Link
  href={{
    pathname: '/about',
    query: { name: 'test' },
  }}
>
  About
</Link>
```

https://nextjs.org/docs/app/api-reference/components/link

2024-04-07 09:48 UTC, WataruNishimura commented on src/components/LinkMenu/LinkMenu.tsx
> +        <div className="bg-transparent flex flex-col gap-[8px] w-[118px]">
gap, widthは具体的な値ではなく、1や2といった規定のspacingを使うようにしてください
8px→2 etc...

2024-04-07 09:48 UTC, WataruNishimura commented on src/components/SpMenu/SpMenu.tsx
> +import LinkMenu from '../LinkMenu/LinkMenu';
folder構造の話ですが同名のフォルダを作る必要は基本的にありません
testを書く場合でも必要ないので直下に羅列してください

2024-04-07 09:48 UTC, WataruNishimura commented on src/app/page.tsx
LinkMenu / SpMenuの実装についてはレイアウトに左右されることもあるので要検討です

2024-04-07 09:48 UTC, WataruNishimura commented on src/components/LinkMenu/LinkMenu.tsx
> +const LINK_STYLE: string = "font-black italic h-[24px] text-center";
clsxを使うようにしてください。また汎用的なスタイルであればtailwind.config.tsへの記載や、constフォルダを作成した上での定数管理をしてください

2024-04-07 09:48 UTC, WataruNishimura commented on src/components/LinkMenu/LinkMenu.tsx
> +import { Button } from "../ui/button";
@components/になるようにしてください

2024-04-07 09:48 UTC, WataruNishimura commented on src/components/LinkMenu/LinkMenu.tsx
> +        <Button variant="link" textSize="lg" justify="normal" asChild>
このlgは定数でかつ変更する可能性の低いものですか？
例えば、デザイン上一回り文字サイズの小さい名称でプライバシーポリシーなどへのリンクを貼る場合があります

そうなければpropsに指定した上でデフォルト値設定するようにしてください

2024-04-07 09:48 UTC, WataruNishimura commented on src/components/LinkMenu/LinkMenu.tsx
> +            <LinkButton text="MAIL" url="mailto:frontendconfhokkaido2024@gmail.com"/>
ユーザーにとって予期せぬ反応になる可能性があります。
目的にもよりますが、問い合わせなどのセクションを作り、CONTACTという形で別記。
問い合わせセクションにメールで問い合わせボタンを作成し、問い合わせさせるという形でもいいかもしれません

2024-04-07 09:48 UTC, WataruNishimura commented on src/components/SpMenu/SpMenu.tsx
> +    const hundleMenuOpen = () => {
typo, hundle > handle

2024-04-07 09:48 UTC, WataruNishimura commented on src/components/SpMenu/SpMenu.tsx
> +            <LinkMenu />
この場合、LinkMenuはクライアントサイドで描画されるためSpMenuコンポーネントのPropsにLinkMenuコンポーネントを渡す形にしてください。

```jsx:page.tsx
<SpMenu menu={<LinkMenu />} />
```

```jsx:SpMenu.tsx
type SpMenuProps = {
  ...
  menu: ReactNode // 適切な型情報にしてください
  ...
}

export default function SpMenu({..., menu}: SpMenuProps) {
  ...
  return (
  ...
  {menu}
  ...
  )
  ...
}
```

2024-04-07 09:48 UTC, WataruNishimura commented on src/components/SpMenu/SpMenu.tsx
> +import { Menu, X } from 'lucide-react';
tailwindを使うのであればheroiconなどがおすすめです（tailwind互換があるため）

https://zenn.dev/nino_cast/books/43c539eb47caab/viewer/807f3b

2024-04-07 13:35 UTC, 618knot commented on src/components/LinkMenu/LinkMenu.tsx
> +            <LinkButton text="MAIL" url="mailto:frontendconfhokkaido2024@gmail.com"/>
#12 で検討とさせてください

2024-04-07 14:02 UTC, 618knot commented on src/components/LinkMenu/LinkMenu.tsx
> +const LINK_STYLE: string = "font-black italic h-[24px] text-center";
実装中の名残でした。
汎用的に使うつもりもなかったため削除します。

2024-04-07 14:04 UTC, 618knot commented on src/components/LinkMenu/LinkMenu.tsx
> +        <Button variant="link" textSize="lg" justify="normal" asChild>
いろいろ勘違いしていたようで、shadcnのbuttonに勝手にvariantを追加してスタイルを無理やり変えていました。
普通にclassNameでやればよいことに気づいたので、いじったvariantは元に戻しました

2024-04-07 14:35 UTC, 618knot commented on src/components/SpMenu/SpMenu.tsx
> +import { Menu, X } from 'lucide-react';
heroiconにしてみました

2024-04-07 14:38 UTC, 618knot commented on src/components/LinkMenu/LinkMenu.tsx
> +import { Button } from "../ui/button";
`Would you like to customize the default import alias (@/*)?`
Noと答えてしまっているので使えないかもしれないです

2024-04-07 14:41 UTC, 618knot commented
@WataruNishimura 
自分でできるところはすべて修正できたと思うので再レビューお願いします 🙇 
- 完全に解消できたと思ったものはresolveしています
- 返信したものと、自信がないところはresolveしないで開けっ放しにしています

2024-04-07 23:42 UTC, WataruNishimura commented on src/components/SpMenu/SpMenu.tsx
> +import { Menu, X } from 'lucide-react';
eslintはconfigファイルの書き方次第っぽいので、少し時間ください

2024-04-10 13:08 UTC, kengo2003 commented
大丈夫だと思います

2024-04-13 00:32 UTC, kengo2003 approved these changes
大丈夫です

2024-04-17 13:26 UTC, WataruNishimura requested changes

2024-04-17 13:26 UTC, WataruNishimura commented on src/components/LinkMenu.tsx
> +            <LinkButton href="mailto:frontendconfhokkaido2024@gmail.com">MAIL</LinkButton>
メールボタンそのまま押すとメールクライアント開くの例えばPCだと想像しづらいと思うのでUI変えた方がいいかもしれませんね
せめて「Send E-mail」とかがいいかな？

2024-04-17 13:27 UTC, WataruNishimura approved these changes

2024-04-18 01:25 UTC, merged