（再）共通ボタンコンポーネントの実装
frontend-conference-hokkaido-2024/landing-page-2024 pull request #110
Opened 2024-05-26 05:25 UTC by kengo2003

## issue番号

#100 
close #100 

## やったこと

## (あえて)やらないこと

## その他

2024-05-28 15:12 UTC, 618knot reviewed
クッション役でコメント残します

閉じるべきissueは95番なので、closeのほうはは95にしてください(100番のほうも関連してるPRなのでlinkは残しておいてよい)

2024-05-28 15:12 UTC, 618knot commented on src/components/ui/CommonButton.tsx
> +    </button>
buttonでflex指定しているので、spanタグはやめていいのではと思います
`px-2.5`を`gap`に置き換えたうえで`text-sm`と`font-bold`と一緒にbuttonのクラスに含めるとよいかと

2024-05-29 11:55 UTC, WataruNishimura requested changes

2024-05-29 11:55 UTC, WataruNishimura commented on src/components/ui/CommonButton.tsx
> +      className={`w-full ${background} text-white rounded-full px-4 py-2.5 flex items-center justify-center`}
アニメーションつけるならgradientとそれ以外で挙動変えた方がいいかもなんですが、 ちょいむずいっすね
UXめちゃできる人間がいるわけでもないので適切に outline css があたってればいいのではという気持ち

https://yuheiy.hatenablog.com/entry/2017/08/18/175321

2024-05-29 11:55 UTC, WataruNishimura commented on src/components/ui/CommonButton.tsx
> +    </button>
spanタグ自分は賛成ですね, 例えば文字要素だけにスタイルをアタッチしたくなったりがあるので

2024-05-29 12:13 UTC, 618knot commented on src/components/ui/CommonButton.tsx
> +    </button>
そのときは自分でspanタグ入れればよいかなーと思ってましたが、ちょっと悩んで書いたところなのでspanタグあってもよいのかもです(確かにiconとかにもcssかかっちゃうかも)

2024-05-30 03:04 UTC, 618knot reviewed
おせっかいを2点ほど

#### 1つめ
毎度
```
#n
close #n
```
と書いていますが、`close #n`と書くだけで十分です(closeの方にリンクがつくので)

#### 2つめ(コミットメッセージについて)
ついやりがちですが、`レビュー修正`というコミットメッセージは情報量がないので単純に何をやったかを書くのがよりよいと思います。

2024-05-31 09:19 UTC, WataruNishimura requested changes

2024-05-31 09:19 UTC, WataruNishimura commented on src/app/page.tsx
> +              className="text-wite"
typo かな？ text-wite → text-white

2024-06-01 13:10 UTC, 618knot approved these changes

2024-06-01 13:11 UTC, merged