メニューリストコンポーネントの実装
frontend-conference-hokkaido-2024/landing-page-2024 pull request #111
Opened 2024-05-30 04:59 UTC by 618knot

## issue番号

close #88

## やったこと
- メニューリストコンポーネントを実装しました
- `TopVisual.tsx`で警告吐いてたので直しました(前にも直した気がする)

## (あえて)やらないこと

## その他

2024-06-02 11:29 UTC, WataruNishimura requested changes

2024-06-04 18:21 UTC, 618knot commented on src/components/menu/MenuList.tsx
> +  const textColor = `text-${color}`;
一旦`white`と`black`しか使わないので、色情報をもろもろオブジェクトで持つようにしました

2024-06-04 18:21 UTC, 618knot commented on src/components/menu/MenuList.tsx
> +      <hr className={clsx("border w-full my-2", borderColor)} />
separatorに差し替えましたー

2024-06-04 18:21 UTC, 618knot commented on src/components/menu/MenuList.tsx
> +      <MenuButton onClick={() => scrollToSection("event-over-view")}>開催概要</MenuButton>
anchorタグで画面内遷移するようにしました

2024-06-06 00:56 UTC, WataruNishimura requested changes

2024-06-06 00:56 UTC, WataruNishimura commented on src/components/menu/MenuList.tsx
> +  color?: "white" | "black";
型パズルの話になっちゃいますが多分以下の感じの方が良いです.
Tailwindから型情報引っ張って来れるといいんだけど
```typescript
type ColorScheme = "white" | "black";

type ColorData = {
  [key: ColorScheme]: {
    text: string;
    border: string;
  }
}

type MenuListProps = {
  color?: ColorScheme
}
```

2024-06-06 00:56 UTC, WataruNishimura commented on src/components/menu/MenuList.tsx
> +        <a href="#event-over-view">
typo `event-overview`
他に一単語もあるので単に`overview`でもいいかも

2024-06-06 00:56 UTC, WataruNishimura commented on src/components/menu/MenuList.tsx
> +        <a href="#online-streaming">
ここも`streaming`とか

2024-06-09 06:03 UTC, merged