チケット購入ボタンエリア実装
frontend-conference-hokkaido-2024/landing-page-2024 pull request #114
Opened 2024-06-01 14:43 UTC by 618knot

## issue番号

close #77 

## やったこと
チケット購入ボタンエリアの実装

## (あえて)やらないこと

チケット購入先のリンクはまだ決まってないと思うので未対応です。

## その他

`Button`を`Link`で囲むのは実装としてどうなのかと思っています(でも右クリで別タブ開きたい..)。`onClick`でa`window.open`するかなど悩みました。

2024-06-02 11:41 UTC, WataruNishimura requested changes

2024-06-02 11:41 UTC, WataruNishimura commented on src/components/TicketButtonArea.tsx
> +        >
asChildでLinkボタンが中に入っている方が, 実装として良い気がします！

2024-06-02 11:41 UTC, WataruNishimura commented on src/components/TicketButtonArea.tsx
> +        >
CommonButtonコンポーネントがasChildに対応してなかったら実装しておいてください

2024-06-02 11:41 UTC, WataruNishimura commented on src/components/TicketButtonArea.tsx
> +export default function TicketButtonArea() {
これはコンポーネントとして表現するのではなくて, そもそもセクション内に書いていてもいい気がするんですが違います？複数配置するから~の理由であればCTAAreaとかの方が個人的にわかりがいいです

2024-06-02 11:41 UTC, WataruNishimura commented on src/components/TicketButtonArea.tsx
> +      <p className="text-caution text-xs font-bold">※オンライン視聴の場合もチケット購入が必要です</p>
smallタグとかでもいいかも

2024-06-04 16:58 UTC, 618knot commented on src/components/TicketButtonArea.tsx
> +export default function TicketButtonArea() {
`CTAArea`に名称変更しましたー

2024-06-04 17:00 UTC, 618knot commented on src/components/TicketButtonArea.tsx
> +        >
現段階で`asChild`は実装されていませんが、実装される前提で`CommonButton`の中に`Link`を置く形にしました

2024-06-04 17:00 UTC, 618knot commented on src/components/TicketButtonArea.tsx
> +      <p className="text-caution text-xs font-bold">※オンライン視聴の場合もチケット購入が必要です</p>
smallタグにしました

2024-06-06 00:59 UTC, WataruNishimura commented on src/components/TicketButtonArea.tsx
> +        >
`asChild`を実装してください...
CommonButton自体はButtonとして有効なので中に`Link`を置くと意図せぬ挙動を起こす可能性があります.

2024-06-06 01:00 UTC, WataruNishimura requested changes
asChild実装の対応とセットでお願いします

2024-06-06 01:35 UTC, 618knot commented on src/components/TicketButtonArea.tsx
> +        >
別PRで`asChild`実装するのでお待ちくださいの意でした(レビューリクエスト飛ばしちゃったのがよろしくなかった)

2024-06-06 01:38 UTC, 618knot commented on src/components/TicketButtonArea.tsx
> +        >
#120

2024-06-06 16:45 UTC, WataruNishimura approved these changes

2024-06-06 16:45 UTC, merged