スポンサー一覧を実装
frontend-conference-hokkaido-2024/landing-page-2024 pull request #117
Opened 2024-06-01 18:39 UTC by ebibibibibi

## issue番号

close #85

## やったこと
- スポンサー一覧を実装

## (あえて)やらないこと

## その他

- Imageのサイズを
```ts
width={65} 
 height={65} 
```
的にベタ打ちしています。他に良い方法があれば教えていただきたいです。

2024-06-02 12:01 UTC, WataruNishimura requested changes

2024-06-12 04:53 UTC, 618knot commented on src/app/@sponsorSection/page.tsx
> +import SponsorList from "./sponsor/sponsorSection";
動作は問題ないので重大ではないですが、renameしたのならば`SponsorList`ではなく`SponsorSection`の名前で呼び出す方がよさそうです

2024-06-12 04:53 UTC, 618knot commented on src/app/@sponsorSection/sponsor/sponsorSection.tsx
> +type SponsorListProps = {
ここも`SponsorSectionProps`?

2024-06-12 04:53 UTC, 618knot commented on src/app/@sponsorSection/sponsor/sponsorSection.tsx
> +        {sponsor.type}
スポンサー名にtype名が出ちゃってる感じがします。ここは`sponsor.typeName`?
(反映まえの暫定的な表示だったらスミマセン)

2024-06-12 04:57 UTC, 618knot commented
あと、念のためdevをpullしておいてもらえると

2024-06-12 13:06 UTC, 618knot approved these changes

2024-06-12 13:07 UTC, merged