チケット購入コンポーネントの実装
frontend-conference-hokkaido-2024/landing-page-2024 pull request #119
Opened 2024-06-05 08:30 UTC by kengo2003

## issue番号

#83 
close #83 

## やったこと
![スクリーンショット 2024-06-05 17 29 49](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/154238842/feeb8805-d0d6-4de4-b86a-f9d6c0e67a3e)

## (あえて)やらないこと

## その他

2024-06-06 01:02 UTC, WataruNishimura requested changes

2024-06-06 01:02 UTC, WataruNishimura commented on src/components/TicketOrder.tsx
> +    <div>
ここのdivにwidthとかpaddingのスタイルが当たってないですが, これ画面広げた時とかに文字が間延びしませんか？

2024-06-06 01:02 UTC, WataruNishimura commented on src/components/TicketOrder.tsx
> +          {"　"}
この空白消してください

2024-06-06 01:02 UTC, WataruNishimura commented on src/components/TicketOrder.tsx
> +          {"　"}チケット販売には, 外部サービス「fortee」を利用しています.
これも、お願いします

2024-06-06 01:02 UTC, WataruNishimura commented on src/components/TicketOrder.tsx
> +        forteeで購入
これだけだとforteeページとばないと思うのでLinkタグを入れるなりしてください...

2024-06-11 01:54 UTC, 618knot reviewed
対応必要そうなところ書いておいたのでよろしくお願いします🙏

(チケット系についてはちょっと相談必要かもしれないので、今日中はステイでもよいかも)

2024-06-11 01:54 UTC, 618knot commented on src/components/TicketOrder.tsx
チケットを販売しているサイトはforteeじゃなくなったので差し替えお願いします

2024-06-11 01:54 UTC, 618knot commented on src/components/TicketOrder.tsx
> +      </CommonButton>
動作確認はしましたか？
`asChild`が当たってなかったり画像が表示されなかったりしていそうなので修正お願いします

2024-06-11 01:59 UTC, 618knot commented
![image](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/82982400/b569939f-f88b-458f-8179-ae15ba4af7a4)
iconの角度も設定してあげてください

2024-06-11 15:57 UTC, 618knot commented
現状はこのままOKなので修正しちゃって大丈夫です！

2024-06-16 06:08 UTC, merged