開催概要の実装
frontend-conference-hokkaido-2024/landing-page-2024 pull request #14
Opened 2024-04-08 14:01 UTC by kengo2003

## issue番号

#{3}
close #{3}

## やったこと
スマホ画面
![スクリーンショット 2024-04-08 0 08 21](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/154238842/f45830f6-56a5-46c2-8b55-6b3cea2a50d0)
PC画面
![スクリーンショット 2024-04-08 22 49 45](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/154238842/5c7430ca-2141-43a3-a1da-6df47e0a4807)

## (あえて)やらないこと

ロゴの画像ができていないので仮タイトルの状態です。
PC画面のnoteとメールアイコンはボタンのみで動作はつけていないです。
PC画面の背景画像のグラデーションは出来ていないです。

## その他

2024-04-08 14:48 UTC, 618knot requested changes
複数指摘ありです
- PCの画面実装は不要です
  - PCサイズでもスマホと同じメインコンテンツを表示する想定です([参考](https://www.pref.saga.lg.jp/airport/bsidesaga/))
  - 共有不足だった可能性があります。すみませんでした。
- 次回からブランチ名は`feature/{issue番号}_{概要}`としてください(今回であれば`feature/3_event_over_view`など)
  - 今回は気にしなくてよいです
- issue番号ですが、 #3  このようにしないとリンクされないです
  - {}は埋め込みの意

2024-04-08 14:48 UTC, 618knot commented on public/Image/mail-icon.png
アイコンを使う場合は、shadcnと一緒についてくる[lucide](https://lucide.dev/icons/)を使用するようにしてください
これについては削除お願いします
( @WataruNishimura やっぱりlucideを使うことにしました。 #2 のiconも後で差し替えます )

2024-04-08 14:48 UTC, 618knot commented on public/Image/note-icon.png
スマホ画面デザインでは、noteのアイコンは使用しません

2024-04-08 14:48 UTC, 618knot commented on src/app/layout.tsx
> +      </body>
勘違いであれば申し訳ありません。
[最新のdevブランチの変更](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/commit/3ebec7ea782954f5e3b6d92e5cc689cb45cea42b)をコピペで取り込んでいませんか？
もしそうであれば、変更はgitコマンドからとりこむようにしてください。

2024-04-08 14:48 UTC, 618knot commented on src/app/page.tsx
こちらも同様に、手動で変更を取り込んでいる場合はgitコマンドで取り込むようにしてください

2024-04-08 14:48 UTC, 618knot commented on src/components/Top/page.tsx
- ディレクトリは以下にファイルを設置する必要はありません
今回であれば`components`直下にファイルを設置してください

- コンポーネントのファイル名とexportするコンポーネント名はアッパーキャメルケースにしてください

2024-04-08 14:48 UTC, 618knot commented on src/components/Top/page.tsx
> +          </button>
buttonはshadcn/uiのButtonコンポーネントを使用するようにしてください
https://ui.shadcn.com/docs/components/button

2024-04-09 10:58 UTC, WataruNishimura requested changes
そのほかの点はKnotくんに同じです！

2024-04-09 10:58 UTC, WataruNishimura commented on public/Image/mail-icon.png
@618knot ok

2024-04-09 10:58 UTC, WataruNishimura commented on public/Image/jingisukan.jpg
publicフォルダ直下は大文字にすることがあまりありません。
具体的に何が問題かと言われると難しいのですが、例えば大文字小文字を区別する処理があった場合に`images`と指定した人がtypoになってしまい参照できないこともあるので基本的にはフォルダは全て小文字で記述しましょう

2024-04-09 10:58 UTC, WataruNishimura commented on public/Image/mail-icon.png
@618knot に追加して、iconを画像として扱うと例えば48px * 48pxにした際に解像度不足でジャギることがあります。svgベクターに変換した上でtsxファイルに転記、適切にマークアップを修正した上でReactコンポーネントとして扱うのがおすすめです

2024-04-09 10:58 UTC, WataruNishimura commented on src/components/Top/page.tsx
> +        width={1000}
width / heightは指定してもいいのですが、指定した際に画像が読み込まれるまでそのサイズでボックスが確保されることになります。今回の場合一旦はsp向けなので同じ比率で画面横幅に合わせたwidthとheightの指定をお勧めします

2024-04-09 10:58 UTC, WataruNishimura commented on src/components/Top/page.tsx
> +        className="z-[-1] lg:w-full hidden lg:block absolute opacity-40"
zindexで負の値を使う場合は、できる限りスタックコンテキストを意識してください。
今回の場合だと全ての要素の一番奥でなく、main要素内で一番奥で良いのであればmainタグにposition: relativeとz-index: autoを指定してください。

2024-04-11 07:54 UTC, 618knot requested changes
2点ほど指摘ありますー

2024-04-11 07:54 UTC, 618knot commented on src/components/page.tsx
> +        </Link>
Linkを使うのであれば、as childとして使用したほうがよいかと思います
https://ui.shadcn.com/docs/components/button
```ts
import Link from "next/link"

import { Button } from "@/components/ui/button"

export function ButtonAsChild() {
  return (
    <Button asChild>
      <Link href="/login">Login</Link>
    </Button>
  )
}

```

2024-04-11 07:54 UTC, 618knot commented on src/components/page.tsx
https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/pull/14#discussion_r1555959568
コンポーネント名とファイル名について修正されていないようなので、修正お願いします

2024-04-13 01:55 UTC, 618knot requested changes
レビューしちゃって良さそうだったので勝手にやっちゃいました
もう一回レビューしてほしいときは画像のリロードボタン押してください～
![image](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/82982400/8a4bfa4b-d9d0-4811-b56a-d90a23d34f99)

自分の方からの指摘はこれで最後かなくらいです。
ほかの細かいところは西村さんが指摘してくれるとおもいます。

2024-04-13 01:55 UTC, 618knot commented on src/components/page.tsx
ファイル名もアッパーキャメルケースで記述してくださいー(ファイル名とコンポーネント名は一致させるようにしてください)
別途指摘しますが、意味のある名前にするようにしてください

2024-04-13 01:55 UTC, 618knot commented on src/components/page.tsx
> +const Page = () => {
`Page.tsx`・`Page`のような命名では、このファイル・コンポーネントが何なのか第三者が見てもわかりません。
「開催概要」のコンポーネントだとわかるような命名をしてみてください。

また、 #6でも`Page.tsx`が新しく作られているためこのままではコンフリクトが発生します。

2024-04-14 06:05 UTC, 618knot requested changes
名前の記述方法についての指摘とタグの使用方法についてだけです

何回も申し訳ないですが、再レビューしてほしいときはgithubからもレビュー依頼を飛ばすようにしてください。
https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/pull/14#pullrequestreview-1998930411

2024-04-14 06:05 UTC, 618knot commented on src/components/Eventoverview.tsx
> +    <main>
mainタグの使いどころには注意かもしれないです(僕もよくわからない)
https://developer.mozilla.org/ja/docs/Web/HTML/Element/main

ここは @WataruNishimura さんのレビューを待ってもいいかも

2024-04-14 06:17 UTC, 618knot commented
あと`close #{3}`になってしまっているので、直しておいていただけると

2024-04-17 05:24 UTC, 618knot requested changes
ファイル名が直っていないのとESLintに怒られているところがあるので修正お願いします🙏

2024-04-17 05:24 UTC, 618knot commented on src/components/Eventoverview.tsx
ファイル名の方もアッパーキャメルケースにしてください

2024-04-17 05:24 UTC, 618knot commented on src/components/Eventoverview.tsx
> +import Image from "next/image";
ESLintに怒られているので解消おねがいします
Reactについては使用していないと思われます
![image](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/82982400/58c4871e-0aef-42e8-ab4e-84ac4ec11cd6)

2024-04-17 06:31 UTC, 618knot commented
画像についても、文字サイズなどの問題から別なものにした方がよいとのことでした。(Discord & Figma参照)
こちらの対応もお願いします

2024-04-17 10:38 UTC, kengo2003 commented on src/components/Eventoverview.tsx
ファイル名も変更してますがgithubに反映されてないです

2024-04-17 10:39 UTC, kengo2003 commented on src/components/Eventoverview.tsx
<img width="1521" alt="スクリーンショット 2024-04-17 19 39 01" src="https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/154238842/49878573-8718-469e-b808-da011e239177">

2024-04-17 10:41 UTC, kengo2003 commented on src/components/Eventoverview.tsx
<img width="675" alt="スクリーンショット 2024-04-17 19 40 53" src="https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/154238842/dd930dda-48b0-41bb-863f-922738b4c5ad">

2024-04-17 11:37 UTC, kengo2003 commented on src/components/Eventoverview.tsx
githubの方に反映されていなかったですが解決しました。

2024-04-17 13:48 UTC, WataruNishimura submitted a review, later dismissed

2024-04-17 13:48 UTC, WataruNishimura commented on src/components/EventOverView.tsx
> +          <li className="flex mr-6">
文字の縦揃えは`margin`ではなく固定の値か`grid`、`table`などを使ってスタイリングしてください

2024-04-17 13:48 UTC, WataruNishimura commented on src/components/EventOverView.tsx
> +            <p className="mr-10 text-slate-600">Date</p>
- ここのDateと下の日付の文字サイズが違うので統一してください
- 文字の縦揃えはmarginではなく固定の値かgrid、tableなどを使ってスタイリングしてください

2024-04-17 13:48 UTC, WataruNishimura commented on src/components/EventOverView.tsx
> +      <Image
- 画像小さい？
- 左に何の隙間もないのが気になります
![CleanShot 2024-04-17 at 22 46 46@2x](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/35600017/c6760049-dd63-4c2f-b2f1-6a059158f515)

2024-04-17 13:48 UTC, WataruNishimura commented on src/components/EventOverView.tsx
> +            <p className="font-bold text-xl">Deep Tech CORE</p>
会場名の正式名称再確認お願いします

2024-04-17 13:48 UTC, WataruNishimura commented on src/components/EventOverView.tsx
> +        <Button asChild>
まだ参加申し込みしないのであれば、ボタンを準備中...などにしてください

2024-04-17 13:48 UTC, WataruNishimura commented on src/components/ui/button.tsx
これ別のPRと混ざってるので気をつけてPR出すか、このファイル除外してPRしてください

2024-04-20 11:41 UTC, 618knot requested changes
### 動作しません
`ui/button.tsx`を削除するコミットが含まれているために、コンパイルエラーが出ています。
https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/pull/14/commits/d1db9b408e94dcb261d090f5ea9652cdb5ce7297

![image](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/82982400/44c212b4-a3b0-4fd3-b91c-1f230131f19c)

レビュー依頼をする際は、最低限動作確認はするようにお願いします。

### コンフリクトしています
以下のファイルは`dev`ブランチとコンフリクトを起こしているため、このままだとdevブランチにマージできません(devブランチに別ブランチがマージされたため)
コンフリクトの解消をお願いします。
**`button.tsx`のようにファイルを削除して、それをコミットする対応はしないでください**
![image](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/82982400/6483cb6d-bbc2-47e7-92e6-03d22976b646)

2024-04-20 11:41 UTC, 618knot commented on .gitignore
gitignoreに`ui/`としてしまうと、別のUIコンポーネントを追加した際にgitに追跡してもらえなくなります。
`ui/`のファイルはgithubに上がっていてほしいので、gitignoreに`ui/`と記述するのは避けてください。

2024-04-20 11:41 UTC, 618knot commented on src/components/EventOverView.tsx
> +import Image from "next/image";
ESLintの警告が解消されていないため、解消お願いします。
(VSCodeに警告が出ていない場合は、拡張機能が入ってないと思われます)
![image](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/82982400/15776e09-b8b4-4c7f-a36e-e7ac3ea9b519)

2024-04-24 09:44 UTC, 618knot requested changes
devからbuttonの変更取り込めば自分の手で編集する必要がないはずなので少し引っ掛かりますが、コンフリクトは解消していそうなのでその点については一旦OKです
2e0c97376960e38024959b1353163d7dd4c5f336
f514c4407add0bb36d52f103d7df1f79a9d1dda1

2024-04-24 09:44 UTC, 618knot commented on src/components/EventOverView.tsx
> +        <Button asChild className="mt-2 w-full text-white text-1xl">
`text-white`はなくても大丈夫だと思います
フォントの太さがfigmaと違います(bold)

2024-04-24 09:44 UTC, 618knot commented on src/components/EventOverView.tsx
> +        </Button>
準備中にもかかわらず、ボタンをクリックできてしまうのはやはりよくないので、ボタンを非活性にしてください
```ts
<Button disabled>
    準備中
</Button>
```
Linkは後から使うのでコメントアウトして`<Link href="#">参加申し込み</Link>`としておいておけばよいかと

2024-04-27 02:51 UTC, 618knot requested changes
細かいところで少しだけあります～

2024-04-27 02:51 UTC, 618knot commented on src/components/EventOverView.tsx
> +        <Button disabled className="mt-2 w-full text-1xl">
フォントの太さがFigmaと違います(bold)

2024-04-27 02:51 UTC, 618knot commented on src/components/EventOverView.tsx
> +        {/* <Button asChild className="mt-2 w-full text-1xl">
フォントの太さがFigmaと違います(bold)

2024-04-27 02:51 UTC, 618knot commented on src/components/EventOverView.tsx
> +    <main className="mt-32">
https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/pull/14#discussion_r1564490880
しばらく考えてみましたが、ここはdivタグにしておきましょうか

2024-04-27 02:51 UTC, 618knot commented on src/components/EventOverView.tsx
> +        alt="アイコンです"
アイコンではないと思うので、変更お願いします。
こんかいは`Frontend Conference HOKKAIDO 2024`とかが適切かなと
https://zenn.dev/snowmount/articles/f9e22df14edab0

2024-04-27 02:54 UTC, 618knot requested changes

2024-04-27 02:54 UTC, 618knot commented on src/components/EventOverView.tsx
> +        <Button disabled className="mt-2 w-full text-1xl">
非活性ボタンを置いてみてもらって思ったのですが、わざわざ準備中ボタンを置く意味がないかも？
参加申し込みが始まるまでは何も置かなくてもいいかもです
(残すか消すかの判断は @kengo2003 くんにお任せします)

2024-04-27 08:10 UTC, kengo2003 commented on src/components/EventOverView.tsx
> +        {/* <Button asChild className="mt-2 w-full text-1xl">
準備中は削除しました

2024-04-29 06:18 UTC, 618knot approved these changes
👌

2024-05-02 16:05 UTC, merged