ジョブボードの単位コンポーネントを実装
frontend-conference-hokkaido-2024/landing-page-2024 pull request #18
Opened 2024-04-21 06:57 UTC by 618knot

## issue番号

close #7 

## やったこと
![image](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/82982400/27bf8de1-980f-47d3-bb37-6fae63306c34)

極力tailwindのユーティリティクラスを使うようにしましたが、どうしようもないとこだけ[px]表記しました

## (あえて)やらないこと

URLからの画像の取得
https://nextjs.org/docs/pages/api-reference/components/image#domains

## その他

2024-04-22 13:54 UTC, WataruNishimura requested changes

2024-04-22 13:54 UTC, WataruNishimura commented on public/images/dummy.svg
このダミー画像って本番環境でも使います？
個人利用か怪しい範囲ですし、元ネタモチーフはコンピューターハッカーかつ犯罪者なのでスポンサーがいる団体が扱うのはイマイチかなと？
https://theghostintheshell.jp/news/ghost-in-the-shell-stand-alone-complex-art-event-2

代替で上げるなら公式ロゴ画像の狐とかカニとかの各モチーフ画像をランダムに出すとかでもいいのかなとか思いますが

2024-04-22 13:54 UTC, WataruNishimura commented on src/app/jobboard/page.tsx
> +      <div className="fixed top-0 left-0 hidden md:block md:w-[calc((100%_-_360px)/4*3)] lg:w-[calc((100%_-_360px)/2)] h-dvh bg-fuchsia-700">
このコンポーネントレイアウト用にまとめてもいいかもしれないですね

2024-04-22 13:54 UTC, WataruNishimura commented on src/components/CompanyCard.tsx
> +    text: string; // 50文字まで
jobCommentかcompanyCommentのほうがいいですね

stringの長さ制約つけるのであればコンポーネント内で文字数でかいとき切り捨てする方法を考えたほうが良いです

2024-04-23 01:41 UTC, 618knot commented on src/app/jobboard/page.tsx
> +      <div className="fixed top-0 left-0 hidden md:block md:w-[calc((100%_-_360px)/4*3)] lg:w-[calc((100%_-_360px)/2)] h-dvh bg-fuchsia-700">
ほかのタイミングでまとめようと思います

2024-04-23 03:53 UTC, 618knot commented on public/images/dummy.svg
ダミーは本番では出ない想定ですが、とりあえずフロントエンドカンファレンスのロゴにしておきました

2024-04-23 03:54 UTC, 618knot commented on src/components/CompanyCard.tsx
> +    text: string; // 50文字まで
renameと文字列切り捨て処理を追加しました

2024-04-23 15:59 UTC, 618knot commented on src/app/jobboard/page.tsx
> +      <div className="fixed top-0 left-0 hidden md:block md:w-[calc((100%_-_360px)/4*3)] lg:w-[calc((100%_-_360px)/2)] h-dvh bg-fuchsia-700">
#22

2024-06-09 07:27 UTC, WataruNishimura commented on src/components/Job.tsx
> +type Job = {
JobPropsにしないと名前被って大丈夫か？という気がしますが...

2024-06-09 07:27 UTC, WataruNishimura approved these changes
引数名ちょい気になりですが, まあ一旦OK

2024-06-09 07:41 UTC, merged