PC版限定のジョブボードへのボタン実装
frontend-conference-hokkaido-2024/landing-page-2024 pull request #192
Opened 2024-07-08 10:42 UTC by kengo2003

## issue番号

#153 
close #153 

## やったこと
<img width="797" alt="スクリーンショット 2024-07-08 19 40 36" src="https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/154238842/58163620-ac88-443c-b1b3-ba55fcca1bba">

## (あえて)やらないこと

## その他

2024-07-08 11:08 UTC, hacusk reviewed
確認をお願いしますー

2024-07-08 11:08 UTC, hacusk commented on src/components/JobButton.tsx
> +    <div className=" hidden lg:flex justify-center">
細かいですが、 `hidden`の左隣の余計な空白は削除してほしいですー

2024-07-08 14:37 UTC, 618knot requested changes
いくつか直してほしいところがあるので対応お願いします。
大急ぎではないので焦らず落ち着いてでだいじょうぶです～

2024-07-08 14:37 UTC, 618knot commented on src/asset/Vector/icon_handshake.svg
自分でiconはアップロードしないで、lucide-reactのiconを使用してください

2024-07-08 14:37 UTC, 618knot commented on src/components/images/icon/Handshake.tsx
自分でiconはアップロードしないで、lucide-reactのiconを使用してください

2024-07-08 14:37 UTC, 618knot commented on src/components/JobButton.tsx
今回のボタンはチケット購入ボタンのように複数個所で使いまわす予定はないので、コンポーネントとして切り出す意味が薄いように思います(何か明確な理由があってこうなったのであれば別ですが。。)

2024-07-08 14:37 UTC, 618knot commented on src/components/JobButton.tsx
> +      <div className="w-3/4">
ここ多少の書き換えは必要かもしれないですが、div要素ひとつにまとめたいです
mx-autoもつかえる

2024-07-08 14:37 UTC, 618knot commented on src/components/JobButton.tsx
> +            rel="noopener noreferrer"
ダメではないですが、自分のところのページなので強制的に別タブで開かせなくてもいいかなと思います

2024-07-08 14:37 UTC, 618knot commented on src/components/JobButton.tsx
> +import Handshake from "./images/icon/Handshake";
lucide-reactのiconを使用してください

2024-07-08 14:37 UTC, 618knot commented on src/app/page.tsx
> +      <JobButton />
もしコンポーネントとして切るにしても、ここに配置してしまうと要素の間隔がおかしいことになります

2024-07-13 09:53 UTC, 618knot reviewed
挙動はOKです～
せっかくなので、CSS(Tailwind)について少し考えてみてください。(余分な≒無意味なクラスが当たっていないかとか)

2024-07-13 09:53 UTC, 618knot commented on src/components/sponsorSection/SponsorSectionView.tsx
> +      <div className="hidden lg:flex justify-center w-3/4 mx-auto mt-8">
細かいですが、今回のケースだと`justify-center`は余分です(意味がないです)。
`justify-center`を消すと`flex`が残りますが、子要素が一つしかなくflexboxを使ったレイアウトをするわけでもないので、`flex`は過剰です。そこで、`flex`の代わりに`block`とするとPC・タブレットの時だけブロック要素として扱ってくれるので、現在と同様の挙動が実現できます。
```suggestion
      <div className="hidden lg:block w-3/4 mx-auto mt-8">
```

2024-07-17 15:15 UTC, 618knot approved these changes
👍 
`lg`だとipad miniやairから見れないようなので、こちらで`md`に修正だけさせてもらいました 🙇

2024-07-17 15:15 UTC, merged