メニューの微修正など
frontend-conference-hokkaido-2024/landing-page-2024 pull request #21
Opened 2024-04-23 15:37 UTC by 618knot

## issue番号

close #12

## やったこと
- LinkMenuのgapを`gap-2`->`gap-3`としました
- SpMenuの背景にグラデーションを付けました
- SpMenuにアニメーションを付けました(開いたときだけ)
- heroiconsを消しました
![image](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/82982400/035d5b44-b994-4e70-96d3-9cb00634864e)

## (あえて)やらないこと

## その他

なくてもいいかなと思ったので、SpMenuを閉じたときはアニメーションかけないようにしてます。

2024-04-24 09:49 UTC, WataruNishimura requested changes

2024-04-24 09:49 UTC, WataruNishimura commented on src/components/LinkMenu.tsx
> +            <LinkButton href="mailto:frontendconfhokkaido2024@gmail.com">SEND E-MAIL</LinkButton>
ここだけ背景黒（真っ黒だとアレなので#111とか）にできますか？誤爆したら泣いちゃいそう

2024-04-24 09:49 UTC, WataruNishimura commented on src/components/LinkMenu.tsx
>                  pathname: "/frontend-conf-hokkaido-2024/proposal/all",
これリンクは仮ですか？STAFF BLOGになっていたので

2024-04-24 09:49 UTC, WataruNishimura commented on src/components/SpMenu.tsx
> +            ? <X className="w-12 h-12 md:hidden lg:hidden" onClick={handleMenuOpen} />
太いかも？線を細くできますか？

2024-04-24 10:08 UTC, 618knot commented on src/components/LinkMenu.tsx
> +            <LinkButton href="mailto:frontendconfhokkaido2024@gmail.com">SEND E-MAIL</LinkButton>
ちょっと考えます

2024-04-24 10:09 UTC, 618knot commented on src/components/LinkMenu.tsx
>                  pathname: "/frontend-conf-hokkaido-2024/proposal/all",
仮リンクではないです

2024-04-25 04:30 UTC, 618knot commented on src/components/LinkMenu.tsx
> +            <LinkButton href="mailto:frontendconfhokkaido2024@gmail.com">SEND E-MAIL</LinkButton>
メールの代わりにXのアカウントを置いてみることにしました

2024-04-27 04:18 UTC, 618knot commented
#22 
こっちとの兼ね合いがありそうなのでいったん放置

2024-05-02 16:11 UTC, merged