Feature/4 event summary
frontend-conference-hokkaido-2024/landing-page-2024 pull request #24
Opened 2024-04-25 06:12 UTC by ebibibibibi

## issue番号

close #4 

## やったこと
イベント概要の実装

## (あえて)やらないこと

## その他

以下動作確認済みです。
- 「公式Xをフォローする」ボタンをクリックした際、遷移が意図通り実現されること
- 「 #frontendo でシェアする」ボタンをクリックした際、遷移が意図通り実現されること

2024-04-26 11:05 UTC, WataruNishimura requested changes

2024-04-26 11:05 UTC, WataruNishimura commented on src/components/EventSummary.tsx
> +            <p className="break-words text-left">
`<br>`は改行の意図ですが、段落を示すのであれば`<p>`がより適切です。

2024-04-26 11:05 UTC, WataruNishimura commented on src/components/EventSummary.tsx
> +                    <Link href="https://twitter.com/fec_hokkaido">
target属性付与しましょう

2024-04-27 03:26 UTC, 618knot requested changes
いくつか指摘あります～

2024-04-27 03:26 UTC, 618knot commented on src/components/EventSummary.tsx
> +import React from 'react';
Reactは使用していないので削除してください

2024-04-27 03:26 UTC, 618knot commented on src/components/EventSummary.tsx
> +                </Button>
`asChild`を付けておいた方がよさそうです
```tsx
import Link from "next/link"

import { Button } from "@/components/ui/button"

export function ButtonAsChild() {
  return (
    <Button asChild>
      <Link href="/login">Login</Link>
    </Button>
  )
}

```

2024-04-27 03:26 UTC, 618knot commented on src/components/EventSummary.tsx
> +            <h3 className="font-semibold text-2xl break-words mb-4">フロントエンドカンファレンス北海道2024を開催します！</h3>
figmaではここの文字サイズは20pxなので、もう少しサイズを小さくしてほしいです

2024-04-27 03:26 UTC, 618knot commented on src/components/EventSummary.tsx
> +import frontend_conference_hokkaido_2024_logo from '@/asset/frontend_conference_hokkaido_2024_logo.png';
import順でESLintに怒られているので解消お願いします。(要VSCode拡張)
![Uploading image.png…]()

2024-04-27 03:26 UTC, 618knot commented on src/components/EventSummary.tsx
> +            <h1 className="text-3xl font-extrabold m-8">イベント概要</h1>
`m-8`だと上にもマージン入ってしまうので、上にはマージンが入らないようにしてください(最後に全部くっつけるときに要素間の間隔を調整するのが面倒になってしまうので)

2024-04-27 06:20 UTC, ebibibibibi commented on src/components/EventSummary.tsx
> +import React from 'react';
削除しました。

2024-04-27 06:20 UTC, ebibibibibi commented on src/components/EventSummary.tsx
> +                </Button>
`asChild` を付けました。

2024-04-27 06:21 UTC, ebibibibibi commented on src/components/EventSummary.tsx
> +import frontend_conference_hokkaido_2024_logo from '@/asset/frontend_conference_hokkaido_2024_logo.png';
ESLintを入れたところ、1行開けろ系の注意が出ていたので、その形で修正しました。

2024-04-27 06:21 UTC, ebibibibibi commented on src/components/EventSummary.tsx
> +            <h1 className="text-3xl font-extrabold m-8">イベント概要</h1>
こちら、基本`mb`を使用する考えで修正を行いました。

2024-04-27 06:21 UTC, ebibibibibi commented on src/components/EventSummary.tsx
> +                    <Link href="https://twitter.com/fec_hokkaido">
target属性を付与しました。

2024-04-27 06:21 UTC, ebibibibibi commented on src/components/EventSummary.tsx
> +        <div style={{ marginLeft: '20px', marginRight: '20px', marginBottom: '50px', textAlign: 'center' }}>
この箇所に限らず、全体的にtailwindに揃えました。

2024-04-27 06:27 UTC, ebibibibibi commented on src/components/EventSummary.tsx
> +            <h3 className="font-semibold text-2xl break-words mb-4">フロントエンドカンファレンス北海道2024を開催します！</h3>
`text-2xl `=>`text-xl`へ変更いたしました。

2024-04-27 06:30 UTC, ebibibibibi commented
@WataruNishimura  @618knot 
いただいたご指摘全て修正完了しております。
お手数ですが、再レビューお願いします 🙇

2024-04-28 02:27 UTC, 618knot reviewed
細かいところで少しコメントあります🙏

2024-04-28 02:27 UTC, 618knot commented on src/components/EventSummary.tsx
> +            <h3 className="font-semibold text-xl break-words mb-4 text-left">フロントエンドカンファレンス北海道2024を開催します！</h3>
デザイン通りではありますが、自分の手元だと
![image](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/82982400/31b177fd-aded-4a28-9420-3156a844f7e5)
こんな感じで中途半端なところで切れてしまっていて少し気になります

「フロントエンドカンファレンス」あたりで改行入れて、text-centerにした方が見栄えはよいかもと思っています

2024-04-28 02:27 UTC, 618knot commented on src/components/EventSummary.tsx
> +                    <Link href="https://twitter.com/intent/tweet?hashtags=frontendo" target="_blank" rel="noopener noreferrer">
ここで何をシェアさせるかは要検討かもしれません
- ハッシュタグ
- 本番環境のURL?
- 何かしらの定型文?

などせっかくならあってもよさそうです

2024-05-02 16:12 UTC, merged