avater実装
frontend-conference-hokkaido-2024/landing-page-2024 pull request #27
Opened 2024-04-30 04:27 UTC by kengo2003

## issue番号

#13 
close #13 

## やったこと
画面
![スクリーンショット 2024-04-30 13 25 26](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/154238842/753b1fbb-ea27-40f4-ab82-313cf297ad2b)

## (あえて)やらないこと

アバターコンポーネントのデータを埋め込む骨組みのみの実装です

## その他

2024-04-30 08:49 UTC, 618knot requested changes

2024-04-30 08:49 UTC, 618knot commented on src/components/Avatar.tsx
> +import React from "react";
使用していないので削除してください

2024-04-30 08:49 UTC, 618knot commented on src/components/Avatar.tsx
> +  alt: string;
optionalにしておくか、alt属性を付けないかにしておいてもよいかと思います

2024-04-30 08:49 UTC, 618knot commented on src/components/Avatar.tsx
> +      />
- 実は枠線があります
![image](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/82982400/b3c1576a-8251-4a48-94c2-cdc45515a9ae)


- ちょっと画像が大きすぎるかも？
![image](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/82982400/0cfbb82d-94c1-404c-9abb-7fa62aaf1800)

2024-04-30 08:49 UTC, 618knot commented on src/components/Avatar.tsx
> +        className="mx-auto py-4 rounded-full"
- 上への余白はなしで大丈夫だと思います
- この場面ではpaddingではなくmarginの方が適していると思います
- 画像と文字の余白についても、もう少し狭いはずです

2024-04-30 08:49 UTC, 618knot commented on src/components/Avatar.tsx
> +      <p className="text-center text-sm font-semibold pb-4 text-black">
下への余白はなしで大丈夫だと思います

2024-05-01 05:00 UTC, kengo2003 commented on src/components/Avatar.tsx
> +      />
枠線をつけて、画像サイズを{150}->{145}に変更しました

2024-05-02 16:15 UTC, merged