アバター一覧コンポーネントを実装
frontend-conference-hokkaido-2024/landing-page-2024 pull request #51
Opened 2024-05-06 23:27 UTC by ebibibibibi

## 23番号

close #

## やったこと
- アバター一覧コンポーネントを実装

## (あえて)やらないこと

- 他のエンドポイントのレスポンスも"https://fortee.jp/frontend-conf-hokkaido-2024/api/staff" と同一の構成になっているを前提とした実装になっています。
- 他エンドポイントのレスポンスの結果を踏まえ、実装の調整が必要になる可能性があります。

## その他

- レスポンスボディに空白が混入している箇所があります。
- 全てのスタッフがAPI出力の準備完了している状況ではなさそうです。

2024-05-07 06:36 UTC, 618knot requested changes

2024-05-07 06:36 UTC, 618knot commented on src/app/page.tsx
> +        <AvatarList avatarListTitle="コアスタッフ" endPointURL= {process.env.FORTEE_API_STAFF} />
どのみちちゃんとした場所に置くので、`</main>`の上に置いておいてもらえると助かります

2024-05-07 06:36 UTC, 618knot commented on src/components/AvatarList.tsx
エラーメッセージがそのまま表示されてしまっているので、エラー時に表示するものについては考える必要がありそうです
![image](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/82982400/41c3a3fb-75f9-4506-a0b6-68d60b2ad2f7)

2024-05-07 06:36 UTC, 618knot commented on src/components/AvatarList.tsx
> +        return data;
この辺りeslintに怒られているので、可能であれば対応お願いします
![image](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/82982400/afb1d5e2-cc74-41f2-aa4a-8de8476724e3)

2024-05-07 06:36 UTC, 618knot commented on src/components/AvatarList.tsx
> +            <Avatar key={person.id}  avatarName={person.name} avatarImage={person.avatar_url} />
アバターurlがとれていない場合、画像が表示されていないようです。(今現在のたかぎとねこさんがその状態)
アバターURLがない場合は何か別のダミー画像で差し替えられているべきです

2024-05-07 06:36 UTC, 618knot commented on src/app/page.tsx
> +  FORTEE_API_STAFF: string;
今回は小規模なので大した問題にはならないかもしれませが、`FORTEE_API_STAFF`のようにして1エンドポイント1環境変数のようにしてしまうと、環境変数がどんどん増えてしまい管理が大変になります。
`.env.local.sample`にある`FORTEE_API_HOST`のように`https://{ドメイン}/api`として、``FORTEE_API_HOST${"/hoge"}``のようにしてエンドポイントを渡すようにしてください。(=`.env.local`で`FORTEE_API_HOST`に値を設定してそれを使うようにしてください)

2024-05-07 15:37 UTC, ebibibibibi commented on src/app/page.tsx
> +        <AvatarList avatarListTitle="コアスタッフ" endPointURL= {process.env.FORTEE_API_STAFF} />
修正しました。

https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/pull/51/commits/458f78851f2116c3d09e210d1c1855f2766d7f91

2024-05-07 15:37 UTC, ebibibibibi commented on src/app/page.tsx
> +  FORTEE_API_STAFF: string;
修正しました。

https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/pull/51/commits/458f78851f2116c3d09e210d1c1855f2766d7f91

2024-05-07 15:38 UTC, ebibibibibi commented on src/components/AvatarList.tsx
> +            <Avatar key={person.id}  avatarName={person.name} avatarImage={person.avatar_url} />
修正しました。

https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/pull/51/commits/eee265415f45ef8a2d2a1c3415cec51dff9e07dc

2024-05-07 15:40 UTC, ebibibibibi commented
@618knot 

レビューの修正対応完了しています。
お手隙の際にご確認お願いいたします。

2024-05-08 02:56 UTC, WataruNishimura requested changes
一旦ここの修正をお願いします

2024-05-08 02:56 UTC, WataruNishimura commented on src/app/page.tsx
> +          <AvatarList avatarListTitle="コアスタッフ" endPointURL={`${process.env.FORTEE_API_HOST}/staff`} />
endpointURLをコンポーネントで取り回すのではなく、APIにアクセスするClientそのものを取り回すか、コンポーネント内で隠蔽してしまうのをお勧めします

コンポーネントの関心事として`どのエンドポイントか`は重要ではなく、このアバターリストは`何の(属性の)`アバターなのかを示す方がいい気がします。

例えばですが、以下のようなイメージです
```javascript
<AvatarList title="コアスタッフ" category="core" />
```

2024-05-08 02:56 UTC, WataruNishimura commented on src/app/page.tsx
> +          <AvatarList avatarListTitle="コアスタッフ" endPointURL={`${process.env.FORTEE_API_HOST}/staff`} />
```javascript
avatarListTitle="コアスタッフ" 
```
ここですが、属性名は`title`とかの方がシンプルで良いですね...

2024-05-08 02:56 UTC, WataruNishimura commented on src/app/page.tsx
> +interface Environment {
ここの型定義をするのであれば、`env.d.ts`などをプロジェクト直下に作成し記述するなどしてください。
上記記述例は正しく機能しない可能性があり、以下をお勧めします。

https://kazuhira-r.hatenablog.com/entry/2023/06/21/231804

```typescript
declare namespace NodeJS {
  interface ProcessEnv {
    readonly FORTEE_API_HOST: string;
  }
}
```

2024-05-08 02:56 UTC, WataruNishimura commented on src/components/Avatar.tsx
> +    <div className="pb-8">
要素と要素の間に空白を開ける場合は、`padding`ではなく`margin`を利用してください。
padding→要素内の空白、margin→要素と他の要素との空白

2024-05-08 02:56 UTC, WataruNishimura commented on src/components/AvatarList.tsx
エラー時はそのコンポーネントごと非表示にしてもいいかもですが、基本はテスト書きましょう...

2024-05-08 02:56 UTC, WataruNishimura commented on src/components/AvatarList.tsx
> +async function getData(url: string):Promise<StaffData> {
```
async function getData<T>(url: string): Promise<T> {}
```

の方が型定義的にはいいかなと....

2024-05-08 02:56 UTC, WataruNishimura commented on src/components/AvatarList.tsx
> +    try {
try-catchはコンポーネント内で書かずに、ErrorBoundaryを利用するなどしてください

https://zenn.dev/hakoten/articles/f5b577d8b63a4a

2024-05-08 02:56 UTC, WataruNishimura commented on src/components/AvatarList.tsx
> +        const responseData: StaffData = await getData(endPointURL);
これだけの処理であれば getData関数を別に宣言せずに`fetch`関数直書きの方がいいかもしれません。
getData関数を別に作るのであれば`src/feature/fortee/api.ts`などを作ってそこで関数宣言する方が今後のためになるかなと...

2024-05-08 02:56 UTC, WataruNishimura commented on src/components/AvatarList.tsx
> +                            avatarImage={person.avatar_url || "/images/Icon-black.png"}
avatar_urlがnullishだったときにicon-black.pngを返したいんだと思うんですが、その場合は
`??`の方が最適です。

2024-05-08 02:56 UTC, WataruNishimura commented on src/components/AvatarList.tsx
> +        const response = await fetch(new Request(url));
fetch関数にはnew Requestではなく、url直渡で大丈夫です

2024-05-08 02:56 UTC, WataruNishimura commented on src/components/AvatarList.tsx
> +        return data;
ignoreでいいかなと

2024-05-12 06:26 UTC, 618knot requested changes
環境変数適当なものにしてみたらエラーメッセージuiに出ちゃってますね
![image](https://github.com/frontend-conference-hokkaido-2024/landing-page-2024/assets/82982400/73dbdd80-f18a-41fc-bf77-ca018c70de85)

2024-05-12 06:26 UTC, 618knot commented on src/components/AvatarList.tsx
> +        <div className="mx-5 mb-12 text-center">
`mb`について、要素間の間隔調整の意図であれば不要です

2024-05-21 14:56 UTC, closed without merging