tailwind.config.tsに固定値を設定
frontend-conference-hokkaido-2024/landing-page-2024 pull request #97
Opened 2024-05-20 07:23 UTC by 618knot

## issue番号

close #93 

## やったこと
`tailwind.config.ts`に4つの固定値を設定

## (あえて)やらないこと

## その他

2024-05-20 09:14 UTC, WataruNishimura requested changes

2024-05-20 09:14 UTC, WataruNishimura commented on tailwind.config.ts
> +        midnightBlue: "#0d172f",
今回のデザインの場合,  black=#0d172fの色として扱うのでblackのextendsのでもいいのかなと言う認識です.

2024-05-20 09:14 UTC, WataruNishimura commented on tailwind.config.ts
> +        darkRed: "#880000",
あとここの場合, darkRedにした上で自作テーマとしてprimaryカラーを立ててdarkRedを参照させる形が良いかなと

2024-05-20 13:49 UTC, 618knot commented on tailwind.config.ts
> +        midnightBlue: "#0d172f",
midnightBlue -> blackにしました

2024-05-20 13:54 UTC, 618knot commented on tailwind.config.ts
> +        darkRed: "#880000",
意図をうまくくみ取れていないかもしれませんが、`--darkRed`のcss変数を設定して`caution`テーマを立てました

2024-05-25 12:14 UTC, WataruNishimura approved these changes

2024-05-25 12:14 UTC, merged